# Generated by Django 6.0.2 on 2026-02-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('purpose', models.CharField(choices=[('medical', 'Medical'), ('recreation', 'Recreation'), ('work', 'Work'), ('visit', 'Visit')], max_length=20)),
                ('cost_level', models.IntegerField(default=1)),
                ('visit_time', models.IntegerField(default=60)),
            ],
        ),
    ]
